In [142]:
from scipy.sparse import coo_matrix
# import numpy
import numpy as np
import pandas as pd

In [143]:
# get data from the csv file
df = pd.read_csv("chicago-taxi-rides.csv")
# throw away the value we don't need
df = df.dropna()
print(df)

      pickup_community_area  dropoff_community_area  trips
0                      14.0                      19   2107
1                      14.0                      24   5370
2                      29.0                      29   2759
3                      29.0                      25    313
4                      41.0                      44   1693
...                     ...                     ...    ...
5412                   14.0                      55      1
5413                   10.0                      65      3
5414                   49.0                      59      2
5416                   20.0                      74      1
5417                   65.0                      12      1

[5400 rows x 3 columns]


In [144]:
dropoff = df["dropoff_community_area"] - 1
pickup = df["pickup_community_area"] - 1
trips = df["trips"]

In [159]:
initial_matrix = coo_matrix((trips, (dropoff, pickup)), shape=(77, 77)).toarray()
print(initial_matrix)
print(initial_matrix[18, 13])

[[110697  28110  41575 ...      2  35848  69417]
 [ 40535 169484  22064 ...      3  30926  44670]
 [ 25228  12978 378179 ...     13  75845 122363]
 ...
 [     5      6     16 ...    635    458     10]
 [ 13054  10569  39343 ...     53 590584  35950]
 [ 46960  29593 118773 ...      6  71246 277895]]
2107


In [160]:
# row_sums = initial_matrix.sum(axis = 1).T
row_sums = initial_matrix.sum(axis = 0)
# t = row_sums
# for i in range(76):
#     row_sums = np.vstack((row_sums, t))
# row_sums = row_sums.T
print(row_sums)
print(np.shape(row_sums))
print(type(row_sums))

[  352130   339222  1612969   465781   637470  6698452  5392832 31595960
     2544    46973   115699    20281    54122   206464    74562   374130
    14242     3339    25973    14082   277587  1161322    41231  3511650
    24724     4560    14348  8328473    11730    14266    91604 21129643
  2169837   104766   122920    12542     4870    29620   106507     9656
   359946    32899    31870    20357     4107     6580      869     5391
    15206     1421     3415      664     2128      378      560  1449419
     6393    13873    80216    38481    12868     5713     4217     8160
     4080     5631     5370     8599    13683     5553     6651     2006
     3461      439     1866  4683744  1039936]
(77,)
<class 'numpy.ndarray'>


In [161]:
initial_matrix = initial_matrix / row_sums
print(initial_matrix)

[[3.14364013e-01 8.28660877e-02 2.57754489e-02 ... 1.07181136e-03
  7.65370609e-03 6.67512232e-02]
 [1.15113736e-01 4.99625614e-01 1.36791222e-02 ... 1.60771704e-03
  6.60283739e-03 4.29545664e-02]
 [7.16439951e-02 3.82581318e-02 2.34461419e-01 ... 6.96677385e-03
  1.61932420e-02 1.17663972e-01]
 ...
 [1.41993014e-05 1.76875321e-05 9.91959548e-06 ... 3.40300107e-01
  9.77850198e-05 9.61597637e-06]
 [3.70715361e-02 3.11565877e-02 2.43916653e-02 ... 2.84030011e-02
  1.26092289e-01 3.45694350e-02]
 [1.33359839e-01 8.72378560e-02 7.36362571e-02 ... 3.21543408e-03
  1.52113352e-02 2.67223175e-01]]


In [162]:
28110 / 339222  

0.08286608769478394

In [163]:
a = np.mat([[1, 2], [3, 4]])
b = np.mat([5
            , 2]).T
print(a / b)

[[0.2 0.4]
 [1.5 2. ]]


In [164]:
bias_matrix = np.full((77, 77), 1/77) * (1 - 0.85)
print(bias_matrix)

[[0.00194805 0.00194805 0.00194805 ... 0.00194805 0.00194805 0.00194805]
 [0.00194805 0.00194805 0.00194805 ... 0.00194805 0.00194805 0.00194805]
 [0.00194805 0.00194805 0.00194805 ... 0.00194805 0.00194805 0.00194805]
 ...
 [0.00194805 0.00194805 0.00194805 ... 0.00194805 0.00194805 0.00194805]
 [0.00194805 0.00194805 0.00194805 ... 0.00194805 0.00194805 0.00194805]
 [0.00194805 0.00194805 0.00194805 ... 0.00194805 0.00194805 0.00194805]]


In [165]:
parameters_matrix = initial_matrix * 0.85 + bias_matrix

In [166]:
print(parameters_matrix)

[[0.26915746 0.07238423 0.02385718 ... 0.00285909 0.0084537  0.05868659]
 [0.09979473 0.42662982 0.01357531 ... 0.00331461 0.00756046 0.03845943]
 [0.06284545 0.03446746 0.20124026 ... 0.00786981 0.01571231 0.10196243]
 ...
 [0.00196012 0.00196309 0.00195648 ... 0.29120314 0.00203117 0.00195623]
 [0.03345886 0.02843115 0.02268097 ... 0.0260906  0.1091265  0.03133207]
 [0.11530391 0.07610023 0.06453887 ... 0.00468117 0.01487769 0.22908775]]


In [167]:
rank = np.full((77, 1), 1 / 77)

In [168]:
print(rank.shape)
print(parameters_matrix)

(77, 1)
[[0.26915746 0.07238423 0.02385718 ... 0.00285909 0.0084537  0.05868659]
 [0.09979473 0.42662982 0.01357531 ... 0.00331461 0.00756046 0.03845943]
 [0.06284545 0.03446746 0.20124026 ... 0.00786981 0.01571231 0.10196243]
 ...
 [0.00196012 0.00196309 0.00195648 ... 0.29120314 0.00203117 0.00195623]
 [0.03345886 0.02843115 0.02268097 ... 0.0260906  0.1091265  0.03133207]
 [0.11530391 0.07610023 0.06453887 ... 0.00468117 0.01487769 0.22908775]]


In [169]:
def fun(times, rank):
    temp = rank
    cache = []
    i = 1
    while (i <= times):
        temp = np.dot(parameters_matrix, temp) 
        if (i % 2 == 0):
            cache.append(temp)
        i += 1
    return cache

In [170]:
ans = fun(64, rank)

In [175]:
print(len(ans))
ans[19]

32


array([[0.00927443],
       [0.01180744],
       [0.02050199],
       [0.01114122],
       [0.01102824],
       [0.05506144],
       [0.04432764],
       [0.17817453],
       [0.00312781],
       [0.00712592],
       [0.0049716 ],
       [0.00443883],
       [0.00560637],
       [0.0072428 ],
       [0.00806994],
       [0.01104936],
       [0.00521397],
       [0.00300135],
       [0.00539857],
       [0.00334825],
       [0.00842496],
       [0.01894636],
       [0.00511897],
       [0.03746813],
       [0.00794261],
       [0.00331042],
       [0.00417021],
       [0.06973776],
       [0.00392513],
       [0.00484024],
       [0.00607736],
       [0.12113669],
       [0.02367982],
       [0.005454  ],
       [0.00740426],
       [0.00333476],
       [0.00391175],
       [0.00546748],
       [0.00514906],
       [0.00398659],
       [0.0117687 ],
       [0.00577044],
       [0.00720681],
       [0.00762257],
       [0.00371797],
       [0.00467001],
       [0.00281891],
       [0.004